### ISSUE TITLE
Issue on Duplicating Linked Nodes in PGD

### ISSUE THREAD

**Issue by LFhase** [THUDM/grb#1]
Hi GRB Team,

When using the latest GRB codebase, I found an issue in your implementation of random injection. For example, in [`/attack/PGD.py`](https://github.com/THUDM/grb/blob/018d5fdf1cc3e4de44c3a6eba49cedc00ea9c66b/grb/attack/pgd.py#L103), an array `islinked` is created but never used, which would lead to repeated connections and hence producing an `adj_attack` with fewer injected edges. May I know whether it is intended or a mistake? Thank you. 😀

**Comment by Stanislas0** [comment]
Hi,

Sorry, it was a code mistake. ``islinked`` should be set 1 after ``yy`` is randomly chosen (``islinked[yy] = 1``). This is originally designed to prevent repeated connections. GRB is still under development, we're currently reviewing all codes and add new interesting features. We welcome any kind of suggestion that helps us improve GRB. Thank you very much for pointing out the problem!

**Comment by Stanislas0** [comment]
Fixed. Refer to https://github.com/THUDM/grb/blob/fe44b053719c52ff5d29fcb6ecf83240ecb24911/grb/attack/pgd.py#L143.
