### ISSUE TITLE
Errors in examples 

### ISSUE THREAD

**Issue by andr2w** [THUDM/grb#9]
I am following the example: Injection_attack.ipynb.
I have trouble in the Apply injection attack section.
I got the AttributeError: row not found.  The adj_attack do not have the attribute .row.
How to solve this problem?

**Comment by Ivyyijing** [comment]
i meet the same problem, and then i change add ".tocoo()" after ".row"".col"".data",seems work

`        adj_attack.tocoo().row = np.hstack([adj_attack.tocoo().row, new_edges_x])
        adj_attack.tocoo().col = np.hstack([adj_attack.tocoo().col, new_edges_y])
        adj_attack.tocoo().data = np.hstack([adj_attack.tocoo().data, new_data])`

**Comment by andr2w** [comment]
> i meet the same problem, and then i change add ".tocoo()" after ".row"".col"".data",seems work
> 
> ` adj_attack.tocoo().row = np.hstack([adj_attack.tocoo().row, new_edges_x]) adj_attack.tocoo().col = np.hstack([adj_attack.tocoo().col, new_edges_y]) adj_attack.tocoo().data = np.hstack([adj_attack.tocoo().data, new_data])`

I have tried this method, but it seems that it only prevents errors without affecting the original `adj_attack` matrix. The reason is as follows: when we call the `adj_attack.tocoo()` method, it creates a new COO format copy of `adj_attack` but doesn't alter the original `adj_attack` matrix.

I have revised the code as follows, I hope this can help you out.

```Python
for i in range(n_inject):
            islinked = np.zeros(n_test)
            for j in range(self.n_edge_max):
                x = i + n_node

                yy = random.randint(0, n_test - 1)
                while islinked[yy] > 0:
                    yy = random.randint(0, n_test - 1)

                y = test_index[yy].item() # so that it will not be [[int, tensor], [int, tensor]]
                islinked[yy] = 1
                new_edges_x.extend([x, y])
                new_edges_y.extend([y, x])
                new_data.extend([1, 1])

        # Create new edges as a COO matrix
        new_edges_coo = sp.coo_matrix((new_data, (new_edges_x, new_edges_y)), shape=(n_node + n_inject, n_node + n_inject))

        add1 = sp.csr_matrix((n_inject, n_node))
        add2 = sp.csr_matrix((n_node + n_inject, n_inject))
        adj_attack = sp.vstack([adj, add1])
        adj_attack = sp.hstack([adj_attack, add2])
        # adj_attack.row = np.hstack([adj_attack.row, new_edges_x])
        # adj_attack.col = np.hstack([adj_attack.col, new_edges_y])
        # adj_attack.data = np.hstack([adj_attack.data, new_data])

        # convert expanded adjacency matrix to COO format for merging
        adj_attack_coo = adj_attack.tocoo()

        # Merge the original (expanded) adjacency matrix with new edges
        adj_attack_new = sp.coo_matrix((np.hstack([adj_attack_coo.data, new_edges_coo.data]),
                                       (np.hstack([adj_attack_coo.row, new_edges_coo.row]),
                                        np.hstack([adj_attack_coo.col, new_edges_coo.col]))),
                                        shape=(n_node + n_inject, n_node + n_inject))

        # convert back to CSR format 
        adj_attack_new_scr = adj_attack_new.tocsr()

        return adj_attack_new_scr
```

**Comment by xz-keg** [comment]
> > i meet the same problem, and then i change add ".tocoo()" after ".row"".col"".data",seems work
> > ` adj_attack.tocoo().row = np.hstack([adj_attack.tocoo().row, new_edges_x]) adj_attack.tocoo().col = np.hstack([adj_attack.tocoo().col, new_edges_y]) adj_attack.tocoo().data = np.hstack([adj_attack.tocoo().data, new_data])`
> 
> I have tried this method, but it seems that it only prevents errors without affecting the original `adj_attack` matrix. The reason is as follows: when we call the `adj_attack.tocoo()` method, it creates a new COO format copy of `adj_attack` but doesn't alter the original `adj_attack` matrix.
> 
> I have revised the code as follows, I hope this can help you out.
> 
> ```python
> for i in range(n_inject):
>             islinked = np.zeros(n_test)
>             for j in range(self.n_edge_max):
>                 x = i + n_node
> 
>                 yy = random.randint(0, n_test - 1)
>                 while islinked[yy] > 0:
>                     yy = random.randint(0, n_test - 1)
> 
>                 y = test_index[yy].item() # so that it will not be [[int, tensor], [int, tensor]]
>                 islinked[yy] = 1
>                 new_edges_x.extend([x, y])
>                 new_edges_y.extend([y, x])
>                 new_data.extend([1, 1])
> 
>         # Create new edges as a COO matrix
>         new_edges_coo = sp.coo_matrix((new_data, (new_edges_x, new_edges_y)), shape=(n_node + n_inject, n_node + n_inject))
> 
>         add1 = sp.csr_matrix((n_inject, n_node))
>         add2 = sp.csr_matrix((n_node + n_inject, n_inject))
>         adj_attack = sp.vstack([adj, add1])
>         adj_attack = sp.hstack([adj_attack, add2])
>         # adj_attack.row = np.hstack([adj_attack.row, new_edges_x])
>         # adj_attack.col = np.hstack([adj_attack.col, new_edges_y])
>         # adj_attack.data = np.hstack([adj_attack.data, new_data])
> 
>         # convert expanded adjacency matrix to COO format for merging
>         adj_attack_coo = adj_attack.tocoo()
> 
>         # Merge the original (expanded) adjacency matrix with new edges
>         adj_attack_new = sp.coo_matrix((np.hstack([adj_attack_coo.data, new_edges_coo.data]),
>                                        (np.hstack([adj_attack_coo.row, new_edges_coo.row]),
>                                         np.hstack([adj_attack_coo.col, new_edges_coo.col]))),
>                                         shape=(n_node + n_inject, n_node + n_inject))
> 
>         # convert back to CSR format 
>         adj_attack_new_scr = adj_attack_new.tocsr()
> 
>         return adj_attack_new_scr
> ```

Thanks a lot for your discovery. It seems to be due to some scipy version problem. We'll have a look at it.

**Comment by xz-keg** [comment]
Similar problem was also in https://github.com/THUDM/tdgia/issues/4 .
